name: CI Tests

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: Test @${{ matrix.os }} / Node.js-${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [24, 'latest']
    env:
      FORCE_COLOR: '1'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test
